config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :tasks
  get "signup" => "users#new"
  resources :users, only:[:new,:create,]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 15}
  
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
  def require_user_logged_in
    redirect_to login_path unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email,password)
      flash[:success] = "ログインしました"
      redirect_to root_path
    else
      flash[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session[:user_id]=nil
    flash[:notice] = "ログアウトしました"
    redirect_to root_path
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  before_action :set_task, only: [:show,:destroy,:edit,:update]
  before_action :require_user_logged_in, only:[:show,:new,:create,:edit,:update,:destroy]
  before_action :correct_user, only: [:destroy,:edit,:update,:show]
  
  
  def index
    if logged_in?
      #@tasks = Task.all.order("created_at DESC").page(params[:page]).per(20)
      @tasks = current_user.task.order("created_at DESC").page(params[:page]).per(20)
    end
  end

  def show
  end

  def new
    @task = current_user.task.build
  end

  def create
    @task = current_user.task.build(task_params)
    
    if @task.save
      flash[:success] = "タスクを登録しました"
      redirect_to @task
    else
      flash[:danger] = "登録できませんでした"
      render :new
    end
  end

  def edit
    
  end

  def update
    if @task.update(task_params)
      flash[:success] = "タスク内容更新！"
      redirect_to @task
    else
      flash[:danger] = "タスク更新失敗！"
      render :edit
    end
  
  
  end

  def destroy
    @task.destroy
    
    flash[:success] = "削除完了！"
    redirect_to tasks_url
  end
  
  
  private
  
  def set_task
    @task = Task.find(params[:id])
  end
  
  def correct_user
    @user = current_user.task.find_by(id: params[:id])
    
    redirect_to root_url unless @user
  end

  def task_params
    params.require(:task).permit(:content,:status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success]="登録が完了しました"
      redirect_to root_path
    else
      flash[:danger] = "登録できませんでした"
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options={size:80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase) 
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type,message| %>
  <div class="alert alert-<%= message_type %> text-center">
    <strong><%= message %></strong>
  </div>

<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle collapse" data-toggle="collapse" data-target="#tasknav">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand " href="/"><strong>
          TASK!!!
        </strong></a>
      </div>
      <div class="collapse navbar-collapse" id="tasknav">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
          <li><%= link_to "新規タスクの登録", new_task_path %></li>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Signup', signup_path %></li>
            <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width initial-scale=1">
    
    <title>Tasklist</title>
    
  <%#セキュリティ対策用コード %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<%# bootstrap用のCSS %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<%# bootstrap用のJavaScript %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    
    <div class="container" >
      <%= render "layouts/flash_messages" %>
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    <!-- 共通フォーム　-->
    <%= form_for(@task) do |f| %>

      
      <% if task.errors.any? %>
       <div class="alert alert-warning" >
         <ul>
          <% task.errors.full_messages.each do |task| %>
          
          <li><%= task %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="form-group">
      <%= f.label :content, "タスク"  %>
      <%= f.text_field :content, class: "form-control"%>
      </div>
      
      <div class="form-group">
      <%= f.label :status, "状況" %>
      <%= f.text_field :status, class: "form-control" %>
      </div>
      
      <%= f.submit "登録", class: "btn btn-primary"  %>
    <% end %>

  </div>
</div>

app/views/tasks/edit.html.erb
<h1 class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">id「<%= @task.id %>」のタスク編集画面</h1>

<%= render "tasks/form", task: @task %>

app/views/tasks/index.html.erb
<% if logged_in? %>

<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= current_user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(current_user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  
<div class="col-xs-8">
  <h1>登録タスク一覧</h1>
  <% if @tasks.any? %>
  
    <table class="table table-striped">
      <thead>
        <tr>
          <th>タスク</th>
          <th>状況</th>
        </tr>
        
      </thead>
      <tbody>
        <% @tasks.each do |task|%>
          <tr>
            <th><%= link_to task.content, task %></th>
            <th><%= task.status %></th>
          </tr>
        <% end %>
        
      </tbody>
    </table>
    
    <div>
      <%= paginate @tasks %>
    </div>
    
  <% end %>
  
  <%= link_to "新規タスクの登録", new_task_path, class: "btn btn-primary" %>
  </div>
</div>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the TASK!!!</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>


<% end %>

app/views/tasks/new.html.erb
<h1 class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">タスク新規登録</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<div class="col-xs-12 col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
  <h1>タスク詳細</h1>
    <table class="table table-bordered">
      <tr>
        <th class="text-center info">タスク</th>
        <td><%= @task.content %></td>
      </tr>
      <tr>
        <th class="text-center info">状況</th>
        <td><%= @task.status %></td>
      </tr>
    </table>
  
  <div class="col-xs-8">
    <% #編集・削除リンク %>
    <%= link_to "編集画面へ", edit_task_path, class:"btn btn-success" %>
    <%= link_to "削除する", @task, method: :delete, data:{confirm: "削除してもよろしいですか？"}, class:"btn btn-danger" %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>